"""initial migrate

Revision ID: 65325fbd7087
Revises: 
Create Date: 2021-10-21 15:55:58.686978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65325fbd7087'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('patient_first_name', sa.String(), nullable=False),
    sa.Column('patient_last_name', sa.String(), nullable=False),
    sa.Column('patient_phone', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('appointment_location', sa.String(length=255), nullable=False),
    sa.Column('appointment_delta', sa.Integer(), nullable=False),
    sa.Column('appointment_time', sa.DateTime(), nullable=False),
    sa.Column('appointment_timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    # ### end Alembic commands ###
