"""initial migration

Revision ID: a1ba787e4200
Revises: 
Create Date: 2021-10-23 17:09:01.154903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ba787e4200'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_first_name', sa.String(), nullable=False),
    sa.Column('patient_last_name', sa.String(), nullable=False),
    sa.Column('patient_phone', sa.String(length=50), nullable=False),
    sa.Column('provider_first_name', sa.String(length=50), nullable=False),
    sa.Column('provider_last_name', sa.String(length=50), nullable=False),
    sa.Column('appointment_location', sa.String(length=255), nullable=False),
    sa.Column('appointment_delta', sa.Integer(), nullable=False),
    sa.Column('appointment_time', sa.DateTime(), nullable=False),
    sa.Column('appointment_timezone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    # ### end Alembic commands ###
